## Data Splitting

Data splitting is a fundamental step in machine learning model development. It involves partitioning a dataset into two or more subsets to train, validate, and test the model's performance. The goal is to ensure that the model generalizes well to unseen data and avoids overfitting. These subsets are often called training, validation, and testing sets.

### Common Data Splitting Techniques

#### 1. Hold-out Validation (Train-Test Split)

This is the simplest and most common technique. The dataset is randomly divided into two subsets: a training set and a test set. Common splits include 70/30, 80/20, or 75/25 for train/test respectively.

The hold-out validation method is simple to implement and fast for large datasets however the model might not be evaluated correctly due to high variance or difference in the distribution of the samples. Hence, the method might not be ideal for small datasets, as the test set might not be representative. The method also does not involve a separate validation set for hyperparameter tuning.

Let's see an example of splitting with `sklearn`

In [86]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [87]:
tips = pd.read_csv("../data/tips.csv")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [88]:
tips.shape

(244, 7)

Assuming our target variable is `tip`, let's split the data into 80% train and 20% test set.

In [89]:
X = tips.drop("tip", axis=1) # Features
y = tips["tip"] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [90]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (195, 6)
X_test shape: (49, 6)
y_train shape: (195,)
y_test shape: (49,)

#### 2. Train-Validation-Test Split

This is an extension of hold-out, where the data is divided into three distinct sets: training, validation, and test. The training set is used for model parameter learining, The validataion set is used for hyperparameter tuning and model selection.

Models with different hyperparameters are trained on the training set and evaluated on the validation set. And the test set is used for final, unbiased evaluation of the chosen model.

The dataset is often splitted into 60/20/20 or 70/15/15 for train/validation/test. This provides a clear separation for training, tuning, and final evaluation, reducing bias in performance estimation. However, the method requires more data than a simple train-test split, which can be an issue for small datasets.

Let's see an example using the tips dataset

In [91]:
X = tips.drop("tip", axis=1) # Features
y = tips["tip"] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

In [92]:
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

X_train shape: (146, 6)
X_val shape: (49, 6)
X_test shape: (49, 6)
y_train shape: (146,)
y_val shape: (49,)
y_test shape: (49,)

#### 3. Stratified Split

This method ensures consistency in group/class distributions across train, validation, and tests. It is often used when dealing with imbalanced classification problems or when we want to make sure outliers are properly represented in each sets.

Let's see an example

In [93]:
tips["sex"].value_counts(normalize=True)

sex
Male      0.643443
Female    0.356557
Name: proportion, dtype: float64

In [94]:
X = tips.drop("tip", axis=1)  # Features
y = tips["tip"]  # Target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, stratify=X["sex"], random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_test, y_test, test_size=0.5, stratify=X_test["sex"], random_state=42
)

In [95]:
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

X_train shape: (146, 6)
X_val shape: (49, 6)
X_test shape: (49, 6)
y_train shape: (146,)
y_val shape: (49,)
y_test shape: (49,)

In [96]:
X_train["sex"].value_counts(normalize=True)

sex
Male      0.643836
Female    0.356164
Name: proportion, dtype: float64

In [97]:
X_val["sex"].value_counts(normalize=True)

sex
Male      0.653061
Female    0.346939
Name: proportion, dtype: float64

In [98]:
X_test["sex"].value_counts(normalize=True)

sex
Male      0.632653
Female    0.367347
Name: proportion, dtype: float64

#### 4. Time Series Split

For time series data, random splitting is inappropriate because it violates the temporal order of data. Time series splitting maintains the chronological order, using past data to predict future data.

Typically, data up to a certain point in time is used for training, and subsequent data is used for testing/validation. This can involve a rolling window approach, where the training window slides forward over time.

This method ensures that the model is evaluated on its ability to forecast future events based on past observations.

Let's see an example using the stocks data set

In [99]:
djones = pd.read_csv("../data/dowjones.csv").set_index("Date")
djones.head()

            Price
Date
1914-12-01  55.00
1915-01-01  56.55
1915-02-01  56.00
1915-03-01  58.30
1915-04-01  66.45

In [100]:
y = djones

y_train, y_test = train_test_split(y, test_size = 0.4, shuffle=False)
y_val, y_test = train_test_split(y_test, test_size=0.5, shuffle=False)

In [101]:
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

y_train shape: (389, 1)
y_val shape: (130, 1)
y_test shape: (130, 1)

In [102]:
y_train.tail()

             Price
Date
1946-12-01  172.91
1947-01-01  176.20
1947-02-01  180.86
1947-03-01  177.12
1947-04-01  172.07

In [103]:
y_val.head()

             Price
Date
1947-05-01  168.71
1947-06-01  172.72
1947-07-01  183.36
1947-08-01  180.69
1947-09-01  177.34

### Cross Validation Sets

This is a more robust technique that involves multiple train-validation splits, and a test split. The dataset is divided into $k$ "folds" (subsets). The model is trained $k$ times, with each fold serving as the validation set exactly once, and the remaining $k-1$ folds forming the training set. After evaluation on the validation sets. Then the model is finally evaluated on the test set.

The key advantages of the method includes:

* **Reduced Variance:** Provides a more reliable estimate of model performance by averaging results over multiple splits.
* **Efficient Use of Data:** All data points are used for both training and validation at some point.
* Better for smaller datasets compared to hold-out methods.

However it also come with certain disadvantages, such as:

* Being computationally more expensive due to multiple training runs.
* Having issues with highly imbalanced datasets if not handled properly (e.g., Stratified K-Fold).

#### Common Cross Validation Split

##### 1. K-Fold Cross-Validation

Here we split the training dataset into $k$ equal-sized folds, where $k \ge 2$. When use these $k$ splits as the validation set and the $k-1$ splits as our training set.

Let's an example using scikit-learn.

In [104]:
from sklearn.model_selection import KFold

First, split the data into train and test sets.

In [105]:
X = tips.drop("tip", axis=1) # Features
y = tips["tip"] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Instantiate the `KFold` splitter

In [ ]:
splitter = KFold(n_splits=5)
splits = splitter.split(X_train, y_train)

for i, (train_idx, val_idx) in enumerate(splits):
    print(f"Fold {i + 1}:")
    print("\t First five indexes (Train Set):", train_idx[:5])
    print("\t First five indexes (Validation Set):", val_idx[:5])
    print("\t Number of sample in train set:", len(X_train.iloc[train_idx]))
    print("\t Number of sample in Validation set:", len(X_train.iloc[val_idx]))

In [ ]:
help(train_idx)

##### 2. Stratified K-Fold Cross-Validation

Here we split the training dataset into $k$ equal-sized folds while also ensuring that consistency in group/class distribution in the training and validation sets.

Let's an example using scikit-learn.

In [107]:
from sklearn.model_selection import StratifiedKFold

First, split the data into train and test sets.

In [108]:
X = tips.drop("tip", axis=1) # Features
y = tips["tip"] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=X["sex"], test_size=0.2, random_state=42)

Instantiate the `KFold` splitter

In [109]:
splitter = StratifiedKFold(n_splits=5)
splits = splitter.split(X_train, X_train["sex"])

for i, (train_idx, val_idx) in enumerate(splits):
    print(f"Fold {i + 1}:")
    print("\t First five indexes (Train Set):", train_idx[:5])
    print("\t First five indexes (Validation Set):", val_idx[:5])
    print("\t Number of sample in train set:", len(X_train.iloc[train_idx]))
    print("\t Number of sample in Validation set:", len(X_train.iloc[val_idx]))
    print(
        "\t Proportion of male and female in train set:",
        X_train.iloc[train_idx]["sex"].value_counts(normalize=True).round(2).to_dict()
    )
    print(
        "\t Proportion of male and female in validation set:",
        X_train.iloc[val_idx]["sex"].value_counts(normalize=True).round(2).to_dict()
    )

Fold 1:
	 First five indexes (Train Set): [38 39 40 41 42]
	 First five indexes (Validation Set): [0 1 2 3 4]
	 Number of sample in train set: 156
	 Number of sample in Validation set: 39
	 Proportion of male and female in train set: {'Male': 0.64, 'Female': 0.36}
	 Proportion of male and female in validation set: {'Male': 0.64, 'Female': 0.36}
Fold 2:
	 First five indexes (Train Set): [0 1 2 3 4]
	 First five indexes (Validation Set): [38 39 40 41 42]
	 Number of sample in train set: 156
	 Number of sample in Validation set: 39
	 Proportion of male and female in train set: {'Male': 0.64, 'Female': 0.36}
	 Proportion of male and female in validation set: {'Male': 0.64, 'Female': 0.36}
Fold 3:
	 First five indexes (Train Set): [0 1 2 3 4]
	 First five indexes (Validation Set): [78 79 80 81 82]
	 Number of sample in train set: 156
	 Number of sample in Validation set: 39
	 Proportion of male and female in train set: {'Male': 0.64, 'Female': 0.36}
	 Proportion of male and female in validation set: {'Male': 0.64, 'Female': 0.36}
Fold 4:
	 First five indexes (Train Set): [0 1 2 3 4]
	 First five indexes (Validation Set): [110 111 113 114 115]
	 Number of sample in train set: 156
	 Number of sample in Validation set: 39
	 Proportion of male and female in train set: {'Male': 0.64, 'Female': 0.36}
	 Proportion of male and female in validation set: {'Male': 0.64, 'Female': 0.36}
Fold 5:
	 First five indexes (Train Set): [0 1 2 3 4]
	 First five indexes (Validation Set): [133 142 144 145 160]
	 Number of sample in train set: 156
	 Number of sample in Validation set: 39
	 Proportion of male and female in train set: {'Male': 0.64, 'Female': 0.36}
	 Proportion of male and female in validation set: {'Male': 0.64, 'Female': 0.36}

##### 3. Leave-One-Out Cross-Validation (LOOCV)

A special case of K-Fold where $k$ is equal to the number of data points ($N$). Each data point serves as the validation set exactly once. It provides a nearly unbiased estimate of generalization error. However, it is extremely computationally expensive for large datasets ($N$ training runs).

It can be implemented by importing `LeaveOneOut` from `sklearn.model_selection`.

### Exercise 1

1. Load the iris data set into a variable named `df`
2. Split the data into train and test sets while ensuring consistency in the distribution of species in both sets.
3. Generate 3 train and validation splits while also ensuring consistency in the distribution of species in the sets.

## Hyperparameter Tunning

Hyperparameter tunning is the process of finding the best/optimal model parameters that gives the best error on the validation sets.

Let's build and tune a lasso regression model using the tips dataset.

In [6]:
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.metrics import root_mean_squared_error as rmse

### Tunning with traditional train and validation sets.

In [7]:
# Split the data
X = tips.drop(["tip", "sex", "smoker", "day", "time"], axis=1) # Features
y = tips["tip"] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

NameError: name 'tips' is not defined

#### Train the model

In [ ]:
lasso_reg = Lasso()
lasso_reg.fit(X_train, y_train)

#### Evaluate the model

In [ ]:
train_pred = lasso_reg.predict(X_train)
val_pred = lasso_reg.predict(X_val)
test_pred = lasso_reg.predict(X_test)

print("Train RMSE:", rmse(y_train, train_pred))
print("Validation RMSE:", rmse(y_val, val_pred))
print("Test RMSE:", rmse(y_test, test_pred))

#### Find optimal regularization term

In [ ]:
# alphas = [0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1.0]
alphas = np.linspace(0.001, 1000, 10000)
validation_errors = []

for reg_term in alphas:
    # Build the model
    lasso_reg = Lasso(alpha=reg_term)
    lasso_reg.fit(X_train, y_train)
    
    # Get predictions
    _val_pred = lasso_reg.predict(X_val)

    # Log the errors
    validation_errors.append(rmse(y_val, _val_pred))

#### 
Check the value of the optimal regurlarization term

In [ ]:
best_error_idx = np.argmin(validation_errors)
alphas[best_error_idx]


The best alpha value is 3.












Rebuild and revaluate the best model.

In [ ]:
# Train the model
lasso_reg = Lasso(alpha=3.0)
lasso_reg.fit(X_train, y_train)

#### Evaluate the model
train_pred = lasso_reg.predict(X_train)
val_pred = lasso_reg.predict(X_val)
test_pred = lasso_reg.predict(X_test)

print("Train RMSE:", rmse(y_train, train_pred))
print("Validation RMSE:", rmse(y_val, val_pred))
print("Test RMSE:", rmse(y_test, test_pred))

#### Tuning using cross validatin splits

In [ ]:


# Split the data
X = tips.drop(["tip", "sex", "smoker", "day", "time"], axis=1) # Features
y = tips["tip"] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
alphas = np.linspace(0.01, 10, 100)
avg_cv_errors = []
splitter = KFold(n_splits=5)

for reg_term in alphas:
    cv_errors = []
    for train_idx, val_idx in splitter.split(X_train, y_train):
        # Get cross validation splits
        _X_train, _y_train = X_train.iloc[train_idx], y_train.iloc[train_idx]
        _X_val, _y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]

        # Build the model
        lasso_reg = Lasso(alpha=reg_term)
        lasso_reg.fit(_X_train, _y_train)
        
        # Get predictions
        _val_pred = lasso_reg.predict(_X_val)

        # Log the errors
        cv_errors.append(rmse(_y_val, _val_pred))
    
    # Log the averge cv error
    avg_cv_errors.append(np.mean(cv_errors))

#### Check optimal average cv error

In [ ]:
avg_cv_errors[:5]

In [ ]:
best_error_idx = np.argmin(avg_cv_errors)
alphas[best_error_idx]

Rebuild and revaluate the best model.

In [ ]:
# Train the model
lasso_reg = Lasso(alpha=0.01)
lasso_reg.fit(X_train, y_train)

# Get train error
train_pred = lasso_reg.predict(X_train)
print("Train RMSE:", rmse(y_train, train_pred))

# Get cross validation errors
cv_errors = []
for train_idx, val_idx in splitter.split(X_train, y_train):
    # Get cross validation splits
    _X_train, _y_train = X_train.iloc[train_idx], y_train.iloc[train_idx]
    _X_val, _y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]

    # Build the model
    lasso_reg = lasso_reg.fit(_X_train, _y_train)
    lasso_reg.fit(_X_train, _y_train)
    
    # Get predictions
    _val_pred = lasso_reg.predict(_X_val)

    # Log the errors
    cv_errors.append(rmse(_y_val, _val_pred))

print("Cross validation RMSEs:", cv_errors)
print("Cross Avg. validation RMSE:", np.mean(cv_errors))

#### Get test errors
test_pred = lasso_reg.predict(X_test)
print("Test RMSE:", rmse(y_test, test_pred))

### 








Tuning with GridSearchCV

Scikit-learn developers already wrote the code that can help us abstract the parameter search and cross validation steps in hyperparameter tuning. Hence we do not need write a new code for the steps unless our evaluation process is something that hasn't been implemented already.

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# Instantiate the model
lasso_reg = Lasso()

# Define the parameter search space
param_grid = {"alpha": np.linspace(0.01, 10, 100)}

# Suppose the model has more than one hyper parameter that we can tune,
# then the parameter grid will be defined as
multi_param_grid = {
    "param1": [1, 2, 3, 4],
    "param2": [1, 2, 3, 4],
    "param3": [1, 2, 3, 4],
}

# Use GridSearchCV to find the optimal parameter
grid_search_cv = GridSearchCV(
    lasso_reg,
    param_grid=param_grid,
    cv=5,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1,
    verbose=1,
)
grid_search_cv.fit(X_train, y_train)

# Get results
results = pd.DataFrame(grid_search_cv.cv_results_)

In [ ]:
results.head()

In [ ]:
# Check best error by sorting the dataframe by "rank_test_score"
results.sort_values("rank_test_score").head()

By default grid search automatically refits the best model, so we can use it to evaluate on the test set directly.

In [ ]:
#### Get test errors
test_pred = grid_search_cv.predict(X_test)
print("Test RMSE:", rmse(y_test, test_pred))

### Exercise 2

1. Load the penguins data set into a variable named `df`

2. Select the numeric features, and used the `sex` column as your target variable. Split the data into train and test sets.

3. Train a logistic regression model with the training set.

4. Use the accuracy score metric to evaluate the model on the training set.

5. Use cross validation method to evaluate the model's accuracy on different subsets of the trainin set.

6. Find the optimal `C` (regularization paramter) of the logistic regression model that gives the highest average accuracy on the validation sets using a for loop.

7. Find the optimal `C` (regularization paramter) of the logistic regression model that gives the highest average accuracy on the validation sets using `GridSearchCV`.

8. Evaluate the model with the best regularization term on the test set.

| Note: `C` is inverse of regularization strength; smaller values specify stronger regularization.

# QUESTION_1_ANSWER

#### Loading the data

In [15]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [16]:
# the necessary libraries have been imported from the start of this note

df = pd.read_csv("../data/penguins.csv")
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [17]:
#  dropping na/null
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [18]:
df.dropna()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

# Q2

In [28]:
NAN_dropped = (df["sex"].dropna(inplace=True))
NAN_dropped

In [20]:
features = df.select_dtypes("number").columns
features
X = df.drop("sex", axis = 1)
y = df["sex"]
X_train, y_train, X_test, y_test = train_test_split(X, y, random_state=42)

In [21]:
print (f"X_train shape: {X_train.shape}")
print (f"X_test shape: {X_test.shape}")
print (f"y_train shape: {y_train.shape}")
print (f"y_test shape: {y_test.shape}")

X_train shape: (258, 6)
X_test shape: (258,)
y_train shape: (86, 6)
y_test shape: (86,)

In [37]:
X_train.astype(int, errors = "ignore")
X_train.astype(float, errors = "ignore")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0
238,Gentoo,Biscoe,46.2,14.5,209.0,4800.0
145,Adelie,Dream,39.0,18.7,185.0,3650.0
209,Chinstrap,Dream,49.3,19.9,203.0,4050.0
...,...,...,...,...,...,...
188,Chinstrap,Dream,47.6,18.3,195.0,3850.0
71,Adelie,Torgersen,39.7,18.4,190.0,3900.0
106,Adelie,Biscoe,38.6,17.2,199.0,3750.0
270,Gentoo,Biscoe,46.6,14.2,210.0,4850.0
102,Adelie,Biscoe,37.7,16.0,183.0,3075.0

# Q3

## Building a logistic regression

In [38]:
X_train.dropna(inplace=True)

In [39]:
features = df.select_dtypes("number").columns
lg_model = LogisticRegression()
lg_model.fit(X_train[features], y_train)
lg_model.legend()

ValueError: y should be a 1d array, got an array of shape (86, 6) instead.

# Q4

In [42]:
alphas = np.linspace(0.001, 1000, 10000)

lasso_reg = Lasso(alpha = 3.0)
lasso_reg.fit(X_train, y_train)

train_pred = lasso_reg.predict(X_train)
test_pred = lasso_reg.predict(X_test)
val_pred = lasso_reg.predict(X_val)

print("Train RMSE: ", rmse(y_tain, train_pred))
print("Validation RMSE: ", rmse(vsl_tain, val_pred))
print("Test RMSE: ", rmse(y_test, test_pred))

ValueError: could not convert string to float: 'Adelie'